//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tread3D.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_LIGHTBULB                   101
#define IDD_TIP                         103
#define IDC_CURSOR_CONSOLE              104
#define IDD_DIALOG_VISGROUP             105
#define CG_IDS_TIPOFTHEDAYMENU          106
#define CG_IDS_DIDYOUKNOW               107
#define CG_IDS_FILE_ABSENT              108
#define CG_IDP_FILE_CORRUPT             109
#define IDC_TREE_ENTITY                 109
#define CG_IDS_TIPOFTHEDAYHELP          110
#define CG_IDS_TIPOFTHEDAY              112
#define IDR_MAINFRAME                   128
#define IDR_TREAD3TYPE                  129
#define IDB_SPLASH                      130
#define IDD_DIALOG_CONSOLE              131
#define IDB_IL_TAB                      136
#define IDR_TOOLBAR_MODES               138
#define IDR_ANCHOR_POPUP                145
#define IDD_DIALOG_TEXTUREBROWSER       146
#define IDR_VISGROUP_POPUP              146
#define IDB_VISGROUP                    148
#define IDD_DIALOG_OBJECT               150
#define IDR_MAIN_POPUP                  151
#define IDD_DIALOG_COLOR                154
#define IDI_ICON_PALETTE                155
#define IDI_ICON_PALETTE2               156
#define IDD_DIALOG_GAMESELECT           157
#define IDB_VERTICAL                    158
#define IDC_BLUE_ARROW                  159
#define IDD_TEXTURE                     160
#define IDC_PROGRESS_STATUS             161
#define IDD_DIALOG_ENTITY               162
#define IDB_ENTITY                      163
#define IDB_BITMAP_POINTER              164
#define IDD_DIALOG_GAMESETUP            169
#define IDB_BITMAP_PAK                  170
#define IDB_BITMAP_DRIVES               171
#define IDD_DIALOG_REGISTER             173
#define IDC_ZOOM                        174
#define IDD_ENTITY_OPTIONS              176
#define IDD_DIALOG_PREVIEW              177
#define IDD_DIALOG_BUILD                178
#define IDI_ICON_CONNECTION             182
#define IDI_ICON_BUILD                  183
#define IDB_BITMAP_CHECK                184
#define IDD_DIALOG_HOLLOW               185
#define IDB_BITMAP_CHECK2               186
#define IDB_IL_TAB2                     187
#define IDB_VISGROUP_DRAG               188
#define IDD_DIALOG_SETUP                189
#define IDD_DIALOG_MODEL                191
#define IDD_DIALOG_MAP                  192
#define IDD_DIALOG_SURFACE              194
#define IDD_DIALOG_SCRIPTS              195
#define IDD_DIALOG_QUICKHELP            196
#define IDI_ICON_TEXLOCK                199
#define IDI_ICON_BACK                   201
#define IDI_ICON_FORWARD                202
#define IDI_ICON_HOME                   203
#define IDI_ICON_CLOSE                  204
#define IDB_SPLASH_MASK                 205
#define IDB_BITMAP_QUICKHELP            207
#define IDI_ICON_ABOUTCLOSE             208
#define IDI_ICON_GLOBE                  209
#define IDI_ICON_CLEAR                  210
#define IDR_MENU_CONSOLE                211
#define IDI_ICON_KEYBOARD               212
#define IDD_DIALOG_ANCHOR               213
#define IDD_DIALOG_AGREEMENT            215
#define IDD_STARTUP_DIALOG              216
#define IDD_DIALOG_KEYS                 217
#define IDR_TOOLBAR_ALIGN               217
#define IDD_DIALOG_ENTITYKEY            219
#define IDR_TOOLBAR_VIEW                226
#define IDR_TOOLBAR_OBJECTS             228
#define IDD_DIALOG_LICENSE              235
#define IDD_ENTITY_FLAGS                236
#define IDD_ENTITY_ANGLE                237
#define IDD_ENTITY_STRING               238
#define IDC_POINTER_MOVE                240
#define IDC_BULB                        1000
#define IDC_STARTUP                     1001
#define IDC_NEXTTIP                     1002
#define IDC_EDIT_CONSOLE                1002
#define IDC_TIPSTRING                   1004
#define IDC_TREE_DIRECTORY              1010
#define IDC_BUTTON_CLEAR                1011
#define IDC_STATIC_WEBPAGE              1011
#define IDC_STATIC_EMAIL1               1012
#define IDC_BUTTON_SAVE                 1012
#define IDC_STATIC_EMAIL2               1013
#define IDC_STATIC_EMAIL3               1014
#define IDC_COMBO_ITEM1                 1015
#define IDC_STATIC_EMAIL4               1015
#define IDC_COMBO_ITEM2                 1016
#define IDC_STATIC_LINE1                1017
#define IDC_STATIC_LINE2                1018
#define IDC_LIST_ITEMS                  1020
#define IDC_STATIC_DISPLAY              1021
#define IDC_BUTTON_COLOR                1022
#define IDC_BUTTON_RESET                1023
#define IDC_TEXTURESIZELIST             1024
#define IDC_LIST_GAMES                  1025
#define IDC_TEXTURELISTBOX              1026
#define IDC_BUTTON_CLOSE                1027
#define IDC_BUTTON_SELECT               1028
#define IDC_BUTTON_BROWSE               1029
#define IDC_COMBO_TEXTURE               1030
#define IDC_LIST_PROPERTIES             1032
#define IDC_STATIC_NAME                 1033
#define IDC_EDIT_FILTER                 1033
#define IDC_BUTTON_FILTER               1034
#define IDC_STATIC_TEXNAME              1035
#define IDC_STATIC_ENTITY               1038
#define IDC_COMBOBOX_VISGROUP           1038
#define IDC_COMBOBOX_CATEGORY           1039
#define IDC_LIST_PATHS                  1042
#define IDC_TAB_MODE                    1043
#define IDC_BUTTON_ADD                  1044
#define IDC_BUTTON_REMOVE               1045
#define IDC_LIST_DIR                    1046
#define IDC_PROGRESS_CONNECT            1047
#define IDC_BUTTON_CONNECT              1048
#define IDC_LIST_MESSAGE                1049
#define IDC_COMBO_OPTIONS               1050
#define IDC_EDIT_FLAGS                  1052
#define IDC_LIST_FLAGS                  1053
#define IDC_EDIT_INPUT                  1054
#define IDC_COMBO_ANGLE                 1055
#define IDC_EDIT_ANGLE                  1056
#define IDC_LIST_TEXTURE                1057
#define IDC_STATIC_CPU                  1058
#define IDC_STATIC_CLOCK                1059
#define IDC_STATIC_REVISION             1060
#define IDC_COMBO_NUMMAP                1061
#define IDC_LIST_SELECTION              1062
#define IDC_LIST_PREVIEW                1062
#define IDC_LIST_SCRIPTS                1062
#define IDC_BUTTON_BUILD                1063
#define IDC_BUTTON_CANCEL               1065
#define IDC_EDIT_COMMAND                1066
#define IDC_LIST_KEYS                   1068
#define IDC_LIST_PROPERRTIES            1068
#define IDC_EDIT_UNITS                  1068
#define IDC_BUTTON_HOLLOW               1069
#define IDC_SLIDER_GAMMA                1071
#define IDC_SLIDER_BACKPLANE            1072
#define IDC_BUTTON_OK                   1072
#define IDC_LIST_OPTOIN                 1074
#define IDC_SLIDER_CURVE                1074
#define IDC_EDIT_KEY                    1075
#define IDC_STATIC_GAMMA                1075
#define IDC_STATIC_CLIPPING             1076
#define IDC_EDIT_EMAIL                  1076
#define IDC_COMBO_TEXMEMORY             1077
#define IDC_STATIC_CURVE                1078
#define IDC_EDIT_CATEGORY               1079
#define IDC_RADIO_BRUSH                 1081
#define IDC_RADIO_MODEL                 1082
#define IDC_BUTTON_CREATE               1083
#define IDC_EDIT_COMMENTS               1084
#define IDC_EDIT_AUTHOR                 1085
#define IDC_CHECK_MASK                  1086
#define IDC_CHECK_AUTOAPPLY             1087
#define IDC_EXPLORER                    1088
#define IDC_ICON_TEXLOCK                1090
#define IDC_STATIC_TEXLOCK              1091
#define IDC_STATIC_BRUSH                1092
#define IDC_STATIC_POINTENTITY          1093
#define IDC_STATIC_SOLIDENTITY          1094
#define IDC_BUTTON_BACK                 1095
#define IDC_BUTTON_FORWARD              1096
#define IDC_BUTTON_HOME                 1097
#define IDC_BUTTON_SITE                 1098
#define IDC_BUTTON_DONE                 1099
#define IDC_PROGRESS_DOWNLOAD           1099
#define IDC_STATIC_STATUS               1100
#define IDC_EDIT_ANCHOR                 1101
#define IDC_BUTTON_SET                  1102
#define IDC_BUTTON_LICENSE              1104
#define IDC_RADIO_SAVE                  1105
#define IDC_RADIO_SAVE_REMINDER         1106
#define IDC_STATIC_OUTPUT               1106
#define IDC_RADIO_SAVE_OFF              1107
#define IDC_BUTTON_ADDKEY               1109
#define IDC_BUTTON_APPLY                1111
#define IDC_BUTTON_GRABTEXTURE          1112
#define IDC_EDIT_VALUE                  1114
#define ID_STATIC_NAME                  1115
#define IDC_EDIT_ROTATION               1117
#define IDC_EDIT_XSHIFT                 1118
#define IDC_EDIT_YSHIFT                 1119
#define IDC_EDIT_XSCALE                 1120
#define IDC_EDIT_YSCALE                 1121
#define IDC_SPIN_ADJUST1                1123
#define IDC_SPIN_ADJUST2                1124
#define IDC_SPIN_ADJUST3                1125
#define IDC_SPIN_ADJUST4                1126
#define IDC_SPIN_ADJUST5                1127
#define IDC_HOTKEY_ENTER                1144
#define IDC_BUTTON_SETKEY               1146
#define IDC_BUTTON_CLEARKEY             1147
#define IDC_BUTTON_UNBINDALL            1148
#define IDC_COMBO_MRU                   1157
#define IDC_EDIT_NAME                   1159
#define IDC_BUTTON_EVALUATE             1163
#define IDC_BUTTON_REGISTER             1164
#define IDC_STATIC_URL                  1165
#define IDC_EDIT_DAYS                   1166
#define IDS_HIDE                        5000
#define IDS_EXPAND                      5001
#define IDS_CONTRACT                    5002
#define IDB_BUTTON_IMAGES               5003
#define IDC_TABCTRLBAR                  5003
#define IDB_BTN_EXPLORER                5006
#define IDB_BTN_ARROW                   5012
#define IDB_BITMAP_CLIP                 5013
#define IDC_VSPLITBAR                   5015
#define IDC_HSPLITBAR                   5016
#define IDC_CURSOR_CONSOLE2             5017
#define ID_VIEW_WORKSPACE               32771
#define ID_VISGROUP_SHOWALL             32772
#define ID_VISGROUP_HIDEALL             32773
#define ID_ADDVISGROUP                  32775
#define ID_VISGROUP_DELETECAT           32776
#define IDT_GRID_COMBO                  32778
#define IDT_ZOOM_COMBO                  32779
#define ID_ANCHOR_REMOVE                32780
#define ID_VISGROUP_ADDCAT              32781
#define ID_OPTIONS_KEYBINDING           32783
#define ID_OPTIONS_DEBUGWINDOW          32784
#define ID_OPTIONS_COLOROPTIONS         32785
#define ID_OPTIONS_GAMESETUP            32786
#define ID_EDIT_DELETE                  32787
#define ID_BUILD_MODEL                  32788
#define IDM_VIEW_OPENGL                 32790
#define IDM_VIEW_GDI                    32791
#define IDM_3D_LINE                     32792
#define IDM_3D_SOLID                    32793
#define IDM_3D_TEXTURED                 32794
#define IDM_3D_REALTIME                 32796
#define IDM_MAP_NOSELBOXSIZE            32798
#define IDM_MAP_NOENTITYFILL            32799
#define IDM_3D_NOBILINEAR               32801
#define IDM_3D_NOSELBOXOUTLINE          32802
#define IDM_MAP_NOENTNAMES              32804
#define IDM_3D_NODRAW                   32805
#define IDT_OBJECT_FLIP_VERTICAL        32810
#define IDT_MODE_PAINT                  32811
#define IDT_OBJECT_FLIP_HORIZONTAL      32812
#define IDT_OBJECT_ROTATE_90_CW         32813
#define IDT_OBJECT_ROTATE_90_CCW        32814
#define IDT_OBJECT_ROTATE_180_CW        32815
#define IDT_OBJECT_CARVE                32816
#define IDT_OBJECT_HOLLOW               32817
#define IDT_OBJECT_GROUP                32818
#define IDT_OBJECT_UNGROUP              32819
#define IDT_OBJECT_PROPERTIES           32820
#define IDT_OBJECT_LINK_ENTITY          32821
#define IDT_OBJECT_UNLINK_ENTITY        32823
#define IDT_VIEW_TOPVIEW                32824
#define IDT_VIEW_SIDEVIEW               32825
#define IDT_VIEW_FRONTVIEW              32826
#define IDT_MODE_CAMERA                 32827
#define IDT_MODE_VERTEX                 32828
#define IDT_MODE_POINTER                32829
#define IDT_MODE_ZOOM                   32830
#define IDT_MODE_FACE                   32831
#define ID_OBJECT_PROPERTIES            32832
#define IDT_MODE_BRUSH                  32833
#define IDT_MODE_CLIP                   32834
#define ID_FILE_EXPORT                  32835
#define IDT_MODE_ENTITY                 32836
#define IDT_MODE_TEXLOCK                32837
#define IDT_RUNMAP                      32838
#define ID_EASTER_EGG                   32840
#define IDM_VISGROUP_DELETE             32841
#define IDM_TREAD_SETUP                 32843
#define ID_VIEW_WORKSPACE2              32844
#define IDM_VIEW_OPENGLSOFT             32845
#define IDM_ENTITY_PATH                 32846
#define IDM_ENTITY_PATHLOOP             32847
#define IDM_ENTITY_TARGETPATH           32848
#define IDM_VIEW_CENTER                 32849
#define IDM_CLEAR_MEMORY                32850
#define IDM_MAP_PROPERTIES              32851
#define IDM_WORLDSPAWN                  32853
#define ID_SCRIPT_INFORMATION           32854
#define ID_QUICK_HELP                   32855
#define ID_CLIP_ACTION                  32856
#define ID_3DVIEW_TRANSPARENTWATER      32859
#define ID_VIEW_SMARTNAMES              32860
#define IDM_ENTITY_DELETEPATH           32861
#define ID_FILE_IMPORT                  32862
#define IDM_3D_DRAWENTITIES             32863
#define IDM_MAP_DRAWPATHS               32864
#define IDM_VIEW_EXPANDCURRENT          32865
#define ID_PLUGIN_TEST                  32866
#define IDM_3D_SHADED                   32867
#define ID_PLUGIN_MENU                  32999
#define ID_PLUGIN_MIN                   33000
#define ID_PLUGIN_MAX                   35000
#define ID_DROP_ANCHOR                  35001
#define ID_GRID_SNAP                    35002
#define ID_VIEW_BRUSH_HANDLES           35003
#define ID_CONSOLE_CLEAR                35004
#define ID_CONSOLE_DUMP                 35005
#define ID_VIEW_ANCHORS                 35006
#define ID_CONSOLE_INFO                 35007
#define ID_VIEW_UPDATEALLVIEWS          35008
#define ID_ALIGN_SIZE_HORIZONTAL        35009
#define ID_ALIGN_SIZE_VERTICAL          35010
#define ID_ALIGN_SIZE_BOTH              35011
#define ID_ALIGN_SPACE_HORIZONTAL       35012
#define ID_ALIGN_SPACE_VERTICAL         35013
#define ID_ALIGN_EDGE_LEFT              35014
#define ID_ALIGN_EDGE_RIGHT             35015
#define ID_ALIGN_EDGE_TOP               35016
#define ID_ALIGN_EDGE_BOTTOM            35017
#define ID_MAP_GRID_SMALLER             35018
#define ID_MAP_GRIDLARGER               35019
#define ID_GRID_LARGER                  35020
#define ID_GRID_SMALLER                 35021
#define ID_VIEW_ANIMATED_SELECTION      35023
#define IDS_INFO1                       61216
#define IDS_INFO2                       61217
#define ID_STATIC                       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        220
#define _APS_NEXT_COMMAND_VALUE         35024
#define _APS_NEXT_CONTROL_VALUE         1110
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
